config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root to: "app_pages#welcome"
  resources :articles do
    resources :comments, module: :articles
  end
  # Actioncable Implementation
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"

  # Action Cable Implementation
  # after_create_commit { CommentJob.perform_later self }

  def comments
    Comment.where(commentable: commentable, parent_id: id)
  end
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/app_pages_controller.rb
class AppPagesController < ApplicationController
  # Main Front Action for users
  def welcome
    # render views/app_pages/welcome.html.erb
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < CommentsController
  before_action :find_article
  private
  def find_article
    @commentable = Article.find(params[:article_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("updated_at DESC")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.save
    redirect_to @commentable
  end
  private
  def comment_params
    params.require(:comment).permit(:parent_id, :body)
  end
end

app/helpers/app_pages_helper.rb
module AppPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/app_pages/welcome.html.erb
<h1 class="display-4 text-center mt-50 main-heading">
  RoR Assignment
</h1>

<div class="container text-center mt-4">
  <%= link_to 'Show all Article', articles_path, class: "main-links" %>
  <%= link_to 'Create a Article', new_article_path, class: "main-links" %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: "form-control form-control-lg", id: "title", placeholder: "Enter the Title of Article" %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: "form-control form-control-lg", placeholder: "Enter Description of Title", rows: "8" %>
  </div>

  <div class="container text-center">
    <%= form.submit "Submit the Article", class: "btn btn-primary form-button" %>
    <%= link_to 'Back', articles_path, class: "btn btn-link" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="display-4 text-center mt-50 main-heading">
  Editing Article
</h1>
<div class="container text-center">
  <%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<% if notice %>
  <div class="alert alert-info text-center" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if @articles.length == 0 %>
  <div class="alert alert-info text-center" role="alert">
    <%= "No Articles to Show" %>
  </div>
<% end %>

<div class="container text-center">

  <h1 class="display-4 text-center mt-30 main-heading">Articles</h1>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
      <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Body</th>
        <th scope="col" colspan="3">Actions</th>
        <th scope="col">Last Updated</th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each_with_index do |article, i| %>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <% if article.title.length > 30 %>
            <td><%= article.title[0..28] + "..." %></td>
          <% else %>
            <td><%= article.title %></td>
          <% end %>
          <% if article.body.length > 30 %>
            <td><%= article.body[0..28] + "..." %></td>
          <% else %>
            <td><%= article.body %></td>
          <% end %>
          <td><%= link_to 'Show', article %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= article.updated_at.strftime("%d/%m/%Y %I:%M %p") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Article', new_article_path, class: "btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<h1 class="display-4 text-center mt-50 main-heading">
  Create a New Article
</h1>
<div class="container text-center">
  <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<div class="container" style="margin-top: 2rem">
  <div class="text-center">
    <p class="article-title">
      <strong>Title:  </strong>
      <%= @article.title %>
    </p>
  </div>

  <p class="article-description">
    <%= simple_format @article.body %>
  </p>

  <div class="text-center">
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary form-button" %>
    <%= link_to 'Back', articles_path, class: "btn btn-link" %>
  </div>
  
  <br />
</div>

<div class="container">
  <%= render partial: "comments/comment_form", locals: {commentable: @article} %>
</div>

<div class="container">
  <h4>
    <span class="badge badge-secondary">
      Comments
    </span>
  </h4>
</div>

<div class="container" id="comments">
  <%= render @article.comments.where(parent_id: nil) %>
</div>

app/views/comments/_comment.html.erb
<div class="card" id="comment-<%= comment.id %>" style="background-color: #ECEFF1; margin: 1rem">
  <div class="card-body" style="padding: 0.5rem; background-color: #ECEFF1;">
    <%= comment.body %>
    <div class="container" style="margin-top: 5px; padding-left: 10px;">
      <button class="btn btn-link btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample-<%= comment.id %>" aria-expanded="false" aria-controls="collapseExample" style="margin: 0px;padding: 0px"> 
        Reply
      </button>
      <div class="collapse" id="collapseExample-<%= comment.id %>">
        <div class="card card-body" style="margin-top: 5px; margin-bottom: 5px; border: 0px transparent;">
          <%= render partial: "comments/comment_form", locals: {commentable: comment.commentable, parent_id: comment.id } %>
        </div>
      </div>
    </div>
    <%= render comment.comments %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="comment-form">
  <%= form_for [commentable, Comment.new], :remote => true do |f| %>
    <div class="form-group" style="margin-top: 10px;">
      <%= f.text_area :body, class: "form-control", id: "title comment-content", placeholder: "Enter Comment" %>
      <%= f.hidden_field :parent_id, value: local_assigns[:parent_id] %>
    </div>
    <div class="comment">
      <%= f.submit "Comment", class: "btn btn-outline-primary btn-sm comment-button" %>
    </div>
    <div class="clr"></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small black mt-10 pt-4">
  <div class="footer-copyright text-center py-3">
    <!-- <%= link_to "RoR Assignment", root_path, style: "color: #263238;" %> -->
  </div>
</footer>

app/views/layouts/_navigation_bar.html.erb
<nav id="navbar-example2" class="navbar navbar-light">
  <%= link_to "RoR", root_path, style: "color: #263238;" %>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to 'New Article', new_article_path, class: "nav-link" %>
    </li>
    <% if !current_person %>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_person_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Login', new_person_session_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item"> 
        <%= link_to 'Log Out', destroy_person_session_path, :method => :delete, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRAssignmentOnlineMagazine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <% if person_signed_in? %> 
      <%= tag :meta, name: 'current-person', data: { id: current_person.id } %> 
    <% end %>
  </head>

  <body>
    <%= render partial: "layouts/navigation_bar" %>
    <% if notice %>
      <div class="alert alert-info text-center" role="alert">
      <%= notice %>
      </div>
    <% end %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>